export const paths = {
	1: {
		ana: '../ProjectFiles-Ana/01 - JavaScript Drum Kit',
		adrian: '../ProjectFiles-Adrian/01 - JavaScript drum kit',
		notes: '../Notes/01-JavaScript-Drum-Kit.md',
		project: 'JavaScript Drum Kit',
		description: 'Turn your keyboard into a drum kit using keyboard events',
	},
	2: {
		ana: '../ProjectFiles-Ana/02 - JS and CSS Clock',
		adrian: '../ProjectFiles-Adrian/02 - JS and CSS clock',
		notes: '../Notes/02-JS-CSS-Clock.md',
		project: 'JS and CSS Clock',
		description: 'build a clock based on current time with rotating clock hands',

	},
	3: {
		ana: '../ProjectFiles-Ana/03 - CSS Variables',
		adrian: '../ProjectFiles-Adrian/03 - CSS variables',
		notes: '../Notes/03-CSS-Variables.md',
		project: 'CSS Variables',
		description: 'Update style using CSS variables',

	},
	4: {
		ana: '../ProjectFiles-Ana/04 - Array Cardio Day 1',
		adrian: '../ProjectFiles-Adrian/04 - Array cardio day 1',
		notes: '../Notes/04-Array-Cardio-Day-1.md',
		project: 'Array Cardio Day 1',
		description: 'Console log exercises practicing array methods such as filter, sort, map, and reduce',
	},
	5: {
		ana: '../ProjectFiles-Ana/05 - Flex Panel Gallery',
		adrian: '../ProjectFiles-Adrian/05 - Flex panel gallery',
		notes: '../Notes/05-Flex-Panel-Gallery.md',
		project: 'Flex Panel Gallery',
		description: 'Using Flexbox to create an accordion like flex gallery',
	},
	6: {
		ana: '../ProjectFiles-Ana/06 - Type Ahead',
		adrian: '../ProjectFiles-Adrian/06 - Type ahead',
		notes: '../Notes/06-Type-Ahead.md',
		project: 'Type Ahead',
		description: ' Display filtered data using the fetch API',
	},
	7: {
		ana: '../ProjectFiles-Ana/07 - Array Cardio Day 2',
		adrian: '../ProjectFiles-Adrian/07 - Array cardio day 2',
		notes: '../Notes/07-Array-Cardio-Day-2.md',
		project: 'Array Cardio Day 2',
		description: 'Console log exercises practicing array methods such as some, every, find, and findIndex',
	},
	8: {
		ana: '../ProjectFiles-Ana/08 - Fun with HTML5 Canvas',
		adrian: '../ProjectFiles-Adrian/08 - Fun with HTML5 canvas',
		notes: '../Notes/08-Fun-with-HTML5-Canvas.md',
		project: 'Fun with HTML5 Canvas',
		description: 'Use HTML5 Canvas to create drawings on 2D context',
	},
	9: {
		ana: '../ProjectFiles-Ana/09 - Dev Tools Domination',
		adrian: '../ProjectFiles-Adrian/09 - DevTools domination',
		notes: '../Notes/09-Dev-Tools-Domination.md',
		project: 'Dev Tools Domination',
		description: 'Dev tools and console log tricks',
	},
	10: {
		ana: '../ProjectFiles-Ana/10 - Hold Shift and Check Checkboxes',
		adrian: '../ProjectFiles-Adrian/10 - Hold Shift and check checkboxes',
		notes: '../Notes/10-Hold-Shift-and-Check-Checkboxes.md',
		project: 'Hold Shift and Check Checkboxes',
		description: 'Apply multi-selection on checkboxes ',
	},
	11: {
		ana: '../ProjectFiles-Ana/11 - Custom Video Player',
		adrian: '../ProjectFiles-Adrian/11 - Custom video player',
		notes: '../Notes/11-Custom-Video-Player.md',
		project: 'Custom Video Player',
		description: 'Create custom video player options such as playback rate and volume control',
	},
	12: {
		ana: '../ProjectFiles-Ana/12 - Key Sequence Detection',
		adrian: '../ProjectFiles-Adrian/12 - Key sequence detection',
		notes: '../Notes/12-Key-Sequence-Detection.md',
		project: 'Key Sequence Detection',
		description: 'Create way to keep track of a key sequence which can unlock an effect with the right combination',
	},
	13: {
		ana: '../ProjectFiles-Ana/13 - Slide in on Scroll',
		adrian: '../ProjectFiles-Adrian/13 - Slide in on scroll',
		notes: '../Notes/13-Slide-in-on-Scroll.md',
		project: 'Slide in on Scroll',
		description: 'Image sliding on scroll animation using window events',
	},
	14: {
		ana: '../ProjectFiles-Ana/14 - JavaScript References VS Copying',
		adrian: '../ProjectFiles-Adrian/14 - JavaScript references vs copying',
		notes: '../Notes/14-JavaScript-References-VS-Copying.md',
		project: 'JavaScript References VS Copying',
		description: 'Examine reference vs. copying using nested data in an array',
	},
	15: {
		ana: '../ProjectFiles-Ana/15 - LocalStorage',
		adrian: '../ProjectFiles-Adrian/15 - LocalStorage',
		notes: '../Notes/15-LocalStorage.md',
		project: 'Local Storage',
		description: 'Store and remove items to local storage with event delegation',
	},
	16: {
		ana: '../ProjectFiles-Ana/16 - Mouse Move Shadow',
		adrian: '../ProjectFiles-Adrian/16 - Mouse move shadow',
		notes: '../Notes/16-Mouse-Move-Shadow.md',
		project: ' Mouse Move Shadow',
		description: 'Apply a dynamic shadow effect on mouse move',
	},
	17: {
		ana: '../ProjectFiles-Ana/17 - Sort Without Articles',
		adrian: '../ProjectFiles-Adrian/17 - Sort without articles',
		project: 'Sort Without Articles',
		description: 'Sort names in array and excluding articles',
	},
	18: {
		ana: '../ProjectFiles-Ana/18 - Adding Up Times with Reduce',
		adrian: '../ProjectFiles-Adrian/18 - Adding up times with reduce',
		project: 'Adding Up Times with Reduce',
		description: 'Add video duration time to get total hours, minutes, and seconds using reduce and map',
	},
	19: {
		ana: '../ProjectFiles-Ana/19 - Webcam Fun',
		adrian: '../ProjectFiles-Adrian/19 - Webcam fun',
		project: 'Webcam Fun',
		description: 'Connect video from web cam to a canvas element and adding effects and filters',
	},
	20: {
		ana: '../ProjectFiles-Ana/20 - Speech Detection',
		adrian: '../ProjectFiles-Adrian/20 - Speech detection',
		notes: '../Notes/20-Speech-Detection.md',
		project: 'Speech Detection',
		description: 'create a speech recognition interface in the browser',
	},
	21: {
		ana: '../ProjectFiles-Ana/21 - Geolocation',
		adrian: '../ProjectFiles-Adrian/21 - Geolocation',
		notes: '../Notes/21-Geolocation.md',
		project: 'Geolocation',
		description: 'Detect heading location and speed of a device',
	},
	22: {
		ana: '../ProjectFiles-Ana/22 - Follow Along Link Highlighter',
		adrian: '../ProjectFiles-Adrian/22 - Follow along link highlighter',
		notes: '../Notes/22-Follow-Along-Link-Highlighter.md',
		project: 'Follow Along Link Highlighter',
		description: 'Add highlight following effect on nav links',
	},
	23: {
		ana: '../ProjectFiles-Ana/23 - Speech Synthesis',
		adrian: '../ProjectFiles-Adrian/23 - Speech synthesis',
		notes: '../Notes/23-Speech-Synthesis.md',
		project: 'Speech Synthesis',
		description: 'Generate speech based on selected voice, rate, and pitch',
	},
	24: {
		ana: '../ProjectFiles-Ana/24 - Sticky Nav',
		adrian: '../ProjectFiles-Adrian/24 - Sticky nav',
		notes: '../Notes/24-Sticky-Nav.md',
		project: 'Sticky Nav',
		description: 'Create sticky nav after scroll',
	},
	25: {
		ana: '../ProjectFiles-Ana/25 - Event Capture, Propagation, Bubbling and Once',
		adrian:
			'../ProjectFiles-Adrian/25 - Event capture_propagation_bubbling_and once',
		notes: '../Notes/25-Event-Propagation.md',
		project: 'Event Capture, Propagation, Bubbling and Once',
		description: 'Apply capture, propagation, bubbling and once to web elements',
	},
	26: {
		ana: '../ProjectFiles-Ana/26 - Stripe Follow Along Nav',
		adrian: '../ProjectFiles-Adrian/26 - Stripe follow along nav',
		notes: '../Notes/26-Stripe-Follow-Along-Nav.md',
		project: 'Stripe Follow Along Nav',
		description: 'displays content on nav link hover with a following smooth animation effect',
	},
	27: {
		ana: '../ProjectFiles-Ana/27 - Click and Drag',
		adrian: '../ProjectFiles-Adrian/27 - Click and drag',
		project: 'Click and Drag',
		description: 'Click and drag accordion with mouse events and positioning',
	},
	28: {
		ana: '../ProjectFiles-Ana/28 - Video Speed Controller',
		adrian: '../ProjectFiles-Adrian/28 - Video speed controller',
		notes: '../Notes/28-Countdown-Timer.md',
		project: 'Video Speed Controller',
		description: 'Video player with draggable input to change video speed',
	},
	29: {
		ana: '../ProjectFiles-Ana/29 - Countdown Timer',
		adrian: '../ProjectFiles-Adrian/29 - Countdown timer',
		project: 'Countdown Timer',
		description: 'Create a timer with preset or custom time increments and displays end time',
	},
	30: {
		ana: '../ProjectFiles-Ana/30 - Whack A Mole',
		adrian: '../ProjectFiles-Adrian/30 - Whack a mole',
		notes: '../Notes/30-Wack-A-Mole.md',
		project: 'Whack A Mole',
		description: 'Create a Whack-a-mole game with random places and show times and keeping track of scores',
	},
};
